name: Deploy Treasure Workflow To Prod instance

on: 
  push:
    branches: main
  
  
jobs:
  deploy_master_to_td_prod:
    runs-on: ubuntu-18.04
    name: deploy to td prod
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: install ruby
        run: sudo apt-get update; sudo apt-get install -y build-essential;

      - name: Install td toolbelt
        run: gem install td

      - name: Run ansible deploy playbook
        env:
          TD_API_KEY: ${{ secrets.td_apikey_tss_onboarding }}
        working-directory: ./deployer
        run: |
          td apikey:set $TD_API_KEY -f;
          ansible-playbook -i ansible.prod.inventory deploy.yml --extra-vars "td_api_key=$TD_API_KEY";
          
          
